package edu.uiowa.icts.inv.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.*;
import edu.uiowa.icts.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @since 10/16/2015 11:14:56 AM CDT
 */
@Entity( name = "edu_uiowa_icts_inv_domain_person" )
@Table( name = "person", schema = "inv" )
@JsonIgnoreProperties( { "hibernateLazyInitializer", "handler" } )
public class Person { 

	private static final Log log = LogFactory.getLog( Person.class );

        private Integer personId;
        private String firstName;
        private String lastName;
        private String username;
        private Boolean consent;
        private Boolean deleted;
        private Integer languageId;
        private String password;
        private String email;
        private Set<PersonRole> personRoles = new HashSet<PersonRole>(0);


    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="inv.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "person_id", unique = true, nullable = false)
    public Integer getPersonId(){
        return personId;
    }

    public void setPersonId(Integer personId){
        this.personId = personId;
    }

    @Column(name = "first_name")
    public String getFirstName(){
        return firstName;
    }

    public void setFirstName(String firstName){
        this.firstName = firstName;
    }

    @Column(name = "last_name")
    public String getLastName(){
        return lastName;
    }

    public void setLastName(String lastName){
        this.lastName = lastName;
    }

    @Column(name = "username")
    public String getUsername(){
        return username;
    }

    public void setUsername(String username){
        this.username = username;
    }

    @Column(name = "consent")
    public Boolean getConsent(){
        return consent;
    }

    public void setConsent(Boolean consent){
        this.consent = consent;
    }

    @Column(name = "deleted")
    public Boolean getDeleted(){
        return deleted;
    }

    public void setDeleted(Boolean deleted){
        this.deleted = deleted;
    }

    @Column(name = "language_id")
    public Integer getLanguageId(){
        return languageId;
    }

    public void setLanguageId(Integer languageId){
        this.languageId = languageId;
    }

    @Column(name = "password")
    public String getPassword(){
        return password;
    }

    public void setPassword(String password){
        this.password = password;
    }

    @Column(name = "email")
    public String getEmail(){
        return email;
    }

    public void setEmail(String email){
        this.email = email;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "person", targetEntity=PersonRole.class, cascade=CascadeType.REMOVE)
    public Set<PersonRole> getPersonRoles(){
        return personRoles;
    }

    public void setPersonRoles(Set<PersonRole> personRoles){
        this.personRoles = personRoles;
    }


}
