package edu.uiowa.icts.inv.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.Task;
import edu.uiowa.icts.inv.domain.WorkLog;
import edu.uiowa.icts.spring.GenericDaoListOptions;
import edu.uiowa.icts.util.WorkLogManager;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:57 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_angular_controller" )
@RequestMapping( "/ng" )
public class AngularController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( AngularController.class );
    
    @ResponseBody
    @RequestMapping( value = "learn.json", method = RequestMethod.GET )
    public String learn(Model model) {
        
        return "{}";
    }
    
    
    
    @RequestMapping( value = "task", method = RequestMethod.GET )
    public String listAngular(Model model) {
        //model.addAttribute( "taskList", invDaoService.getTaskService().list() );
        return "/ng/task";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list( ModelMap model) {
        model.addAttribute( "task", new Task() );
 		model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );
 		model.addAttribute( "taskTypeList", invDaoService.getTaskTypeService().list() );

        return "/inv/task/list";
    }

    @RequestMapping( value = { "mine" }, method = RequestMethod.GET )
    public String myTasklist( ModelMap model) {
        model.addAttribute( "task", new Task() );
 		model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );
 		model.addAttribute( "taskTypeList", invDaoService.getTaskTypeService().list() );

        return "/inv/task/mine";
    }
   
}