package edu.uiowa.icts.inv.controller;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_message_controller" )
@RequestMapping( "/message" )
public class MessageController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( MessageController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "messageList", invDaoService.getMessageService().list() );
        return "/inv/message/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/inv/message/list";
    }

	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		DataTable dt = new DataTable();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = invDaoService.getMessageService().count( options );
            List<Message> messageList = invDaoService.getMessageService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( Message message : messageList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					if( StringUtils.equals( "messageId", headerName ) ){
						tableRow.put( dataName, message.getMessageId() );
					} else if( StringUtils.equals( "messageName", headerName ) ){
						tableRow.put( dataName, message.getMessageName() );
					} else if( StringUtils.equals( "messageType", headerName ) ){
						tableRow.put( dataName, message.getMessageType() );
					} else if( StringUtils.equals( "version", headerName ) ){
						tableRow.put( dataName, message.getVersion() );
					} else if( StringUtils.equals( "messageText", headerName ) ){
						tableRow.put( dataName, message.getMessageText() );
					} else if( StringUtils.equals( "irbApproval", headerName ) ){
						tableRow.put( dataName, message.getIrbApproval() );
					} else if( StringUtils.equals( "irbApprovalStartDate", headerName ) ){
						tableRow.put( dataName, message.getIrbApprovalStartDate() );
					} else if( StringUtils.equals( "irbApprovalEndDate", headerName ) ){
						tableRow.put( dataName, message.getIrbApprovalEndDate() );
					} else if( StringUtils.equals( "description", headerName ) ){
						tableRow.put( dataName, message.getDescription() );
					} else if( StringUtils.equals( "urls", headerName ) ) {
						String urls = "";
						if( StringUtils.equals( "list", display ) ){
							urls += "<a href=\"" + contextPath + "/message/show?"+"messageId="+message.getMessageId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
							urls += "<a href=\"" + contextPath + "/message/edit?"+"messageId="+message.getMessageId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
							urls += "<a href=\"" + contextPath + "/message/delete?"+"messageId="+message.getMessageId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
						} else {

						}
						tableRow.put( dataName, urls );
					} else {
						tableRow.put( "error", "[error: column " + headerName + " not supported]" );
					}
				}
				data.add( tableRow );
			}

			dt.setDraw( dataTableRequest.getDraw() );
            dt.setRecordsFiltered( count );
            dt.setRecordsTotal( count );
			dt.setData( data );

		} catch ( Exception e ) {
			log.error( "error builing datatable json object for Message", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
		return dt;
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "message", new Message() );

        return "/inv/message/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "messageId" ) Integer messageId ) {


        model.addAttribute( "message", invDaoService.getMessageService().findById( messageId ) );
        return "/inv/message/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "messageId" ) Integer messageId ) {

        model.addAttribute( "message", invDaoService.getMessageService().findById( messageId ) );
        return "/inv/message/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "message" ) Message message, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
			
			return "/inv/message/edit"; 
		} else {
			try {
				invDaoService.getMessageService().saveOrUpdate( message );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				invDaoService.getMessageService().merge( message );
			}
		}
		return "redirect:/message/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "messageId" ) Integer messageId ) {

        model.addAttribute( "message", invDaoService.getMessageService().findById( messageId ) );
        return "/inv/message/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "messageId" ) Integer messageId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            invDaoService.getMessageService().delete( invDaoService.getMessageService().findById( messageId ) );
        }
        return "redirect:/message/list";
    }
}