package edu.uiowa.icts.inv.controller;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:57 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_person_controller" )
@RequestMapping( "/person" )
public class PersonController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( PersonController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "personList", invDaoService.getPersonService().list() );
        return "/inv/person/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/inv/person/list";
    }

	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		DataTable dt = new DataTable();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = invDaoService.getPersonService().count( options );
            List<Person> personList = invDaoService.getPersonService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( Person person : personList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					if( StringUtils.equals( "personId", headerName ) ){
						tableRow.put( dataName, person.getPersonId() );
					} else if( StringUtils.equals( "firstName", headerName ) ){
						tableRow.put( dataName, person.getFirstName() );
					} else if( StringUtils.equals( "lastName", headerName ) ){
						tableRow.put( dataName, person.getLastName() );
					} else if( StringUtils.equals( "username", headerName ) ){
						tableRow.put( dataName, person.getUsername() );
					} else if( StringUtils.equals( "consent", headerName ) ){
						tableRow.put( dataName, person.getConsent() );
					} else if( StringUtils.equals( "deleted", headerName ) ){
						tableRow.put( dataName, person.getDeleted() );
					} else if( StringUtils.equals( "languageId", headerName ) ){
						tableRow.put( dataName, person.getLanguageId() );
					} else if( StringUtils.equals( "password", headerName ) ){
						tableRow.put( dataName, person.getPassword() );
					} else if( StringUtils.equals( "email", headerName ) ){
						tableRow.put( dataName, person.getEmail() );
					} else if( StringUtils.equals( "personRoles", headerName ) ){
						tableRow.put( dataName, person.getPersonRoles().size() );
					} else if( StringUtils.equals( "urls", headerName ) ) {
						String urls = "";
						if( StringUtils.equals( "list", display ) ){
							urls += "<a href=\"" + contextPath + "/person/show?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
							urls += "<a href=\"" + contextPath + "/person/edit?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
							urls += "<a href=\"" + contextPath + "/person/delete?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
						} else {

						}
						tableRow.put( dataName, urls );
					} else {
						tableRow.put( "error", "[error: column " + headerName + " not supported]" );
					}
				}
				data.add( tableRow );
			}

			dt.setDraw( dataTableRequest.getDraw() );
            dt.setRecordsFiltered( count );
            dt.setRecordsTotal( count );
			dt.setData( data );

		} catch ( Exception e ) {
			log.error( "error builing datatable json object for Person", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
		return dt;
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "person", new Person() );

        return "/inv/person/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {


        model.addAttribute( "person", invDaoService.getPersonService().findById( personId ) );
        return "/inv/person/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {

        model.addAttribute( "person", invDaoService.getPersonService().findById( personId ) );
        return "/inv/person/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "person" ) Person person, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
			
			return "/inv/person/edit"; 
		} else {
			try {
				invDaoService.getPersonService().saveOrUpdate( person );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				invDaoService.getPersonService().merge( person );
			}
		}
		return "redirect:/person/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {

        model.addAttribute( "person", invDaoService.getPersonService().findById( personId ) );
        return "/inv/person/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "personId" ) Integer personId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            invDaoService.getPersonService().delete( invDaoService.getPersonService().findById( personId ) );
        }
        return "redirect:/person/list";
    }
}