package edu.uiowa.icts.inv.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/18/2015 08:25:18 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_property_controller" )
@RequestMapping( "/property" )
public class PropertyController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( PropertyController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );
        return "/inv/property/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/inv/property/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = invDaoService.getPropertyService().count( options );
            List<Property> propertyList = invDaoService.getPropertyService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( Property property : propertyList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "propertyId" :
							tableRow.put( dataName, property.getPropertyId() );
							break;
						case "name" :
							tableRow.put( dataName, property.getName() );
							break;
						case "description" :
							tableRow.put( dataName, property.getDescription() );
							break;
						case "createdBy" :
							tableRow.put( dataName, property.getCreatedBy() );
							break;
						case "created" :
							tableRow.put( dataName, property.getCreated() );
							break;
						case "updatedBy" :
							tableRow.put( dataName, property.getUpdatedBy() );
							break;
						case "updated" :
							tableRow.put( dataName, property.getUpdated() );
							break;
						case "tasks" :
							tableRow.put( dataName, property.getTasks().size() );
							break;
						case "workLogs" :
							tableRow.put( dataName, property.getWorkLogs().size() );
							break;
						case "location" :
							if( property.getLocation() != null ){
								tableRow.put( dataName, property.getLocation().toString() );
							}
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/property/show?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/property/edit?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/property/delete?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for Property", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "property", new Property() );
		model.addAttribute( "locationList", invDaoService.getLocationService().list() );

        return "/inv/property/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {
		model.addAttribute( "locationList", invDaoService.getLocationService().list() );


        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "property" ) Property property, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "locationList", invDaoService.getLocationService().list() );

			return "/inv/property/edit"; 
		} else {
			try {
				invDaoService.getPropertyService().saveOrUpdate( property );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				invDaoService.getPropertyService().merge( property );
			}
		}
		return "redirect:/property/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            invDaoService.getPropertyService().delete( invDaoService.getPropertyService().findById( propertyId ) );
        }
        return "redirect:/property/list";
    }
}