package edu.uiowa.icts.inv.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/26/2015 17:44:58 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_worklog_controller" )
@RequestMapping( "/worklog" )
public class WorkLogController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( WorkLogController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "workLogList", invDaoService.getWorkLogService().list() );
        return "/inv/worklog/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/inv/worklog/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = invDaoService.getWorkLogService().count( options );
            List<WorkLog> workLogList = invDaoService.getWorkLogService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( WorkLog workLog : workLogList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "taskId" :
							tableRow.put( dataName, workLog.getTaskId() );
							break;
						case "name" :
							tableRow.put( dataName, workLog.getName() );
							break;
						case "created" :
							tableRow.put( dataName, workLog.getCreated() );
							break;
						case "createdBy" :
							tableRow.put( dataName, workLog.getCreatedBy() );
							break;
						case "assignedTo" :
							tableRow.put( dataName, workLog.getAssignedTo() );
							break;
						case "deadline" :
							tableRow.put( dataName, workLog.getDeadline() );
							break;
						case "completed" :
							tableRow.put( dataName, workLog.getCompleted() );
							break;
						case "note" :
							tableRow.put( dataName, workLog.getNote() );
							break;
						case "taskType" :
							if( workLog.getTaskType() != null ){
								tableRow.put( dataName, workLog.getTaskType().toString() );
							}
							break;
						case "property" :
							if( workLog.getProperty() != null ){
								tableRow.put( dataName, workLog.getProperty().toString() );
							}
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/worklog/show?"+"taskId="+workLog.getTaskId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/worklog/edit?"+"taskId="+workLog.getTaskId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/worklog/delete?"+"taskId="+workLog.getTaskId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for WorkLog", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "workLog", new WorkLog() );
		model.addAttribute( "taskTypeList", invDaoService.getTaskTypeService().list() );
		model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );

        return "/inv/worklog/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "taskId" ) Integer workLogId ) {
		model.addAttribute( "taskTypeList", invDaoService.getTaskTypeService().list() );
		model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );


        model.addAttribute( "workLog", invDaoService.getWorkLogService().findById( workLogId ) );
        return "/inv/worklog/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "taskId" ) Integer workLogId ) {

        model.addAttribute( "workLog", invDaoService.getWorkLogService().findById( workLogId ) );
        return "/inv/worklog/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "workLog" ) WorkLog workLog, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "taskTypeList", invDaoService.getTaskTypeService().list() );
		model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );

			return "/inv/worklog/edit"; 
		} else {
			try {
				invDaoService.getWorkLogService().saveOrUpdate( workLog );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				invDaoService.getWorkLogService().merge( workLog );
			}
		}
		return "redirect:/worklog/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "taskId" ) Integer workLogId ) {

        model.addAttribute( "workLog", invDaoService.getWorkLogService().findById( workLogId ) );
        return "/inv/worklog/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "taskId" ) Integer workLogId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            invDaoService.getWorkLogService().delete( invDaoService.getWorkLogService().findById( workLogId ) );
        }
        return "redirect:/worklog/list";
    }
}