package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.spring.AbstractSpringTestCase;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.web.WebAppConfiguration;

/**
 * Unit test Template
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/18/2015 07:52:59 CDT
 */
@WebAppConfiguration
public class WorkLogTest extends AbstractSpringTestCase {

    @Autowired
    private InvDaoService invDaoService;

    @Test
    public void testServiceName() {
    	assertEquals( true, true );
    }

    @Before
    public void setUp() throws Exception {
    	super.setUp();
    }

    @After
    public void tearDown() throws Exception {
    	super.tearDown();
    }

}