package edu.uiowa.icts.inv.web;

import java.util.HashMap;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.ExceptionHandler;
import edu.uiowa.icts.inv.dao.InvDaoService;
import edu.uiowa.icts.spring.Security;


/**
 * Generated by Protogen
 * @since 10/16/2015 11:14:56 CDT
 */
public abstract class AbstractInvResource {

	protected InvDaoService invDaoService;

	@Autowired
	public void setInvDaoService( InvDaoService invDaoService ) {
		this.invDaoService = invDaoService;
	}

	@ModelAttribute( value = "username" )
	public String getUsername() {
		if ( Security.isAuthenticated() ) {
			return SecurityContextHolder.getContext().getAuthentication().getName();
		}
		return null;
	}
	

}