package edu.uiowa.icts.inv.resource;


import java.util.List;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Arrays;

import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.datatable.DataTableSearch;
import edu.uiowa.icts.inv.dao.*;
import edu.uiowa.icts.inv.domain.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import edu.uiowa.icts.inv.controller.AbstractControllerMVCTests;

/**
 * Generated by Protogen
 * @since Fri Oct 16 11:14:57 CDT 2015
 */
public class MessageResourceMvcTest extends AbstractControllerMVCTests {
	
    private Message firstMessage;
    private ObjectMapper mapper;
    
    @Before
    public void before() {
              // add 20 records to test database
        for(int x=1; x<21; x++){
        	Message message = new Message();
        	invDaoService.getMessageService().save(message);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstMessage = message;
	        }
        }   
        this.mapper = new ObjectMapper();
        // fix NonUniqueObjectException
        this.invDaoService.getMessageService().getSession().flush();
        this.invDaoService.getMessageService().getSession().clear();
          }    
    
            
	    @Test
	    public void getByPathVariableIdShouldLoadAndReturnObject() throws Exception {
	    	mockMvc.perform(get("/api/message/"+firstMessage.getMessageId().toString()))
	         .andExpect(status().isOk())
	         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	        .andExpect(jsonPath("$.messageId", is(firstMessage.getMessageId())))
	        ;
	    }
      
	    @Test
	    public void getByPathVariableIdShouldReturn404ForBogusId() throws Exception {
	    	mockMvc.perform(get("/api/message/-123")).andExpect(status().isNotFound()).andExpect(jsonPath("$.message", is("/api/message/-123 could not be found.")));
	    }
	    
	    @Test
	    public void restMappingNotFoundShouldReturn404() throws Exception {
	    	mockMvc.perform(get("/api/message/asdfasdf/asdfasdf"))
	    	.andExpect(status().isNotFound())
	    	 .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	        .andExpect(jsonPath("$.message", is("/api/message/asdfasdf/asdfasdf could not be found.")))
	    	;
	    }
	    
	    @Test
	    public void createShouldPersistAndReturnObject() throws Exception {
		   long count = invDaoService.getMessageService().count();	       
		   Message message = new Message(); 
	       
	       mockMvc.perform(post("/api/message/").content(this.mapper.writeValueAsString(message))
		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
	       .andExpect(status().isOk())
	       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	       .andExpect(jsonPath("$.messageId").value(IsNull.notNullValue()))  
	       ;
	       
	       assertEquals("count should increase by 1", count +1 , invDaoService.getMessageService().count());
		}
	     
	    @Test
	    public void updateShouldPersistExistingAndReturnObject() throws Exception {
	       long count = invDaoService.getMessageService().count();

	       mockMvc.perform(post("/api/message/"+ firstMessage.getMessageId().toString())
	    		   .content(this.mapper.writeValueAsString(firstMessage))
	    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
	       .andExpect(status().isOk())
	       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	       .andExpect(jsonPath("$.messageId", is(firstMessage.getMessageId())))
	       ;
	         
	       assertEquals("count NOT should increase", count , invDaoService.getMessageService().count());
	  	}  
	    
	    @Test
	    public void updateByPathVariableIdShouldReturn404ForMismatchBetweenPathIdAndObjectId() throws Exception {	       
	       String correctId =  firstMessage.getMessageId().toString();
	       // this ID manipulation should be overwritten with path variable id
	       firstMessage.setMessageId(-123);
	       
	       mockMvc.perform(post("/api/message/"+correctId)
	    		   .content(this.mapper.writeValueAsString(firstMessage))
	    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
	       .andExpect(status().isNotFound())
	       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	       .andExpect(jsonPath("$.message", is("/api/message/" +correctId +" could not be found.")))
	       ;
	  	} 
	    
	    @Test
	    public void updateByPathVariableIdShouldReturn404ForBogusPathId() throws Exception {
	    	mockMvc.perform(post("/api/message/-123")
	    			.content(this.mapper.writeValueAsString(firstMessage))
	    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
	    	.andExpect(status().isNotFound())
	    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
		    .andExpect(jsonPath("$.message", is("/api/message/-123 could not be found.")));
	    }
	    
	    @Test
	    public void deleteShouldDeleteAndReturnStatusOk() throws Exception {
	        long count = invDaoService.getMessageService().count();

	        mockMvc.perform(delete("/api/message/"+ firstMessage.getMessageId().toString()))
	       .andExpect(status().isOk());  
	       
	       assertEquals("count should decrease by 1", count - 1 , invDaoService.getMessageService().count());
	    }
	    
	    @Test
	    public void deleteShouldFailWithBogusId() throws Exception {
	        long count = invDaoService.getMessageService().count();

	        mockMvc.perform(delete("/api/message/-123"))
	       .andExpect(status().isNotFound())
	       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	       .andExpect(jsonPath("$.message", is("/api/message/-123 could not be found.")));  
	       
	       assertEquals("count should NOT decrease by 1", count , invDaoService.getMessageService().count());
	    }
    
	    @Test
	    public void listShouldReturnAllByDefault() throws Exception {
	    	mockMvc.perform(get("/api/message/"))
	         .andExpect(status().isOk())
	         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	         .andExpect(jsonPath("$.", hasSize(is(20))))
	        .andExpect(jsonPath("$.[0].messageId", is(firstMessage.getMessageId())))
	        ;
	    }
	    
	    @Test
	    public void listShouldReturnAllByDefaultWithoutTrailUrlSlash() throws Exception {
	    	mockMvc.perform(get("/api/message"))
	         .andExpect(status().isOk())
	         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	         .andExpect(jsonPath("$.", hasSize(is(20))))
	        .andExpect(jsonPath("$.[0].messageId", is(firstMessage.getMessageId())))
	        ;
	    }
      }