package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_MessageHome" )
public class MessageHome extends GenericDao<Message> implements MessageService {

	public MessageHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Message" );
	}

	public Message findById( Integer id ) {
		return (Message) this.sessionFactory.getCurrentSession().get( Message.class, id );
	}

	@Override
	public Message getCurrentMessage(String messageName) {
		Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Message.class);
		criteria.add(Restrictions.eq("messageName", messageName));
		criteria.addOrder(Order.desc("version"));
		criteria.setMaxResults(1);
		return (Message) criteria.uniqueResult();
	}

	@Override
	public Integer getCurrentMessageId(String messageName) {
		Integer id = null;
		Message m = getCurrentMessage(messageName);
		if( m != null ){
			id = m.getMessageId();
		}
		return id;
	}

	@Override
	public String getCurrentMessageText(String messageName) {
		String text = null;
		Message m = getCurrentMessage(messageName);
		if( m != null ){
			text = m.getMessageText();
		}
		return text;
	}
}