package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_PersonRoleHome" )
public class PersonRoleHome extends GenericDao<PersonRole> implements PersonRoleService {

	public PersonRoleHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.PersonRole" );
	}

	public PersonRole findById( Integer id ) {
		return (PersonRole) this.sessionFactory.getCurrentSession().get( PersonRole.class, id );
	}

}