package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_PersonHome" )
public class PersonHome extends GenericDao<Person> implements PersonService {

	public PersonHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Person" );
	}

	public Person findById( Integer id ) {
		return (Person) this.sessionFactory.getCurrentSession().get( Person.class, id );
	}

}