package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_PropertyHome" )
public class PropertyHome extends GenericDao<Property> implements PropertyService {

	public PropertyHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Property" );
	}

	public Property findById( Integer id ) {
		return (Property) this.sessionFactory.getCurrentSession().get( Property.class, id );
	}

}