package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_RoleHome" )
public class RoleHome extends GenericDao<Role> implements RoleService {

	public RoleHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Role" );
	}

	public Role findById( Integer id ) {
		return (Role) this.sessionFactory.getCurrentSession().get( Role.class, id );
	}

}