package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_SystemSettingHome" )
public class SystemSettingHome extends GenericDao<SystemSetting> implements SystemSettingService {

	public SystemSettingHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.SystemSetting" );
	}

	public SystemSetting findById( String id ) {
		return (SystemSetting) this.sessionFactory.getCurrentSession().get( SystemSetting.class, id );
	}

	public String getValue(String name, String defaultVal){
		Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(SystemSetting.class);
		criteria.add(Restrictions.eq("name", name));
		SystemSetting set = (SystemSetting) criteria.uniqueResult();
		if (set != null) {
			return set.getValue();
		} else {
			return defaultVal;
		}
	}
}