package edu.uiowa.icts.inv.dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import edu.uiowa.icts.inv.domain.Person;
import edu.uiowa.icts.inv.domain.Task;
import edu.uiowa.icts.spring.GenericDao;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_TaskHome" )
public class TaskHome extends GenericDao<Task> implements TaskService {

	public TaskHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Task" );
	}

	public Task findById( Integer id ) {
		return (Task) this.sessionFactory.getCurrentSession().get( Task.class, id );
	}

	
	public List<Task> listByPerson(String username) {
	     Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Task.class);
	     criteria.add(Restrictions.eq("assignedTo", username));
	     return criteria.list();
	}

}