package com.schappet.inv.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import com.schappet.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @date 07/03/2014 13:14:00 CDT
 */ 

@Entity(name="com_schappet_inv_domain_person")
@Table(name = "person", schema="inv")
public class Person { 

	private static final Log log = LogFactory.getLog(Person.class);

        private Integer personId;
        private String firstName;
        private String lastName;
        private String username;
        private Boolean consent;
        private Boolean deleted;
        private Integer languageId;
        private String password;

    public Person()    {
        this.personId = null;
        this.firstName = "";
        this.lastName = "";
        this.username = "";
        this.consent = null;
        this.deleted = null;
        this.languageId = null;
        this.password = "";
    }

    public Person(Integer personId, String firstName, String lastName, String username, Boolean consent, Boolean deleted, Integer languageId, String password)
    {
        this.personId = personId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.consent = consent;
        this.deleted = deleted;
        this.languageId = languageId;
        this.password = password;
    }

    /*****personId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="inv.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "person_id", unique = true, nullable = false)
    public Integer getPersonId(){
        return personId;
    }

    public void setPersonId(Integer personId){
        this.personId = personId;
    }

    /*****firstName*****/
    @Column(name = "first_name")
    public String getFirstName(){
        return firstName;
    }

    public void setFirstName(String firstName){
        this.firstName = firstName;
    }

    /*****lastName*****/
    @Column(name = "last_name")
    public String getLastName(){
        return lastName;
    }

    public void setLastName(String lastName){
        this.lastName = lastName;
    }

    /*****username*****/
    @Column(name = "username")
    public String getUsername(){
        return username;
    }

    public void setUsername(String username){
        this.username = username;
    }

    /*****consent*****/
    @Column(name = "consent")
    public Boolean getConsent(){
        return consent;
    }

    public void setConsent(Boolean consent){
        this.consent = consent;
    }

    /*****deleted*****/
    @Column(name = "deleted")
    public Boolean getDeleted(){
        return deleted;
    }

    public void setDeleted(Boolean deleted){
        this.deleted = deleted;
    }

    /*****languageId*****/
    @Column(name = "language_id")
    public Integer getLanguageId(){
        return languageId;
    }

    public void setLanguageId(Integer languageId){
        this.languageId = languageId;
    }

    /*****password*****/
    @Column(name = "password")
    public String getPassword(){
        return password;
    }

    public void setPassword(String password){
        this.password = password;
    }


}
