package com.schappet.inv.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import com.schappet.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @date 07/03/2014 13:14:00 CDT
 */ 

@Entity(name="com_schappet_inv_domain_property")
@Table(name = "property", schema="inv")
public class Property { 

	private static final Log log = LogFactory.getLog(Property.class);

        private Integer propertyId;
        private String name;
        private String description;
        private String createdBy;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date created;
        private String updatedBy;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date updated;
        private Set<Task> tasks = new HashSet<Task>(0);
        private Location location;

    public Property()    {
        this.propertyId = null;
        this.name = "";
        this.description = "";
        this.createdBy = "";
        this.created = null;
        this.updatedBy = "";
        this.updated = null;
        this.tasks = new HashSet<Task>(0);
        this.location = null;
    }

    public Property(Integer propertyId, String name, String description, String createdBy, Date created, String updatedBy, Date updated, Set<Task> tasks, Location location)
    {
        this.propertyId = propertyId;
        this.name = name;
        this.description = description;
        this.createdBy = createdBy;
        this.created = created;
        this.updatedBy = updatedBy;
        this.updated = updated;
        this.tasks = tasks;
        this.location = location;
    }

    /*****propertyId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="inv.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "property_id", unique = true, nullable = false)
    public Integer getPropertyId(){
        return propertyId;
    }

    public void setPropertyId(Integer propertyId){
        this.propertyId = propertyId;
    }

    /*****name*****/
    @Column(name = "name")
    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    /*****description*****/
    @Column(name = "description")
    public String getDescription(){
        return description;
    }

    public void setDescription(String description){
        this.description = description;
    }

    /*****createdBy*****/
    @Column(name = "created_by")
    public String getCreatedBy(){
        return createdBy;
    }

    public void setCreatedBy(String createdBy){
        this.createdBy = createdBy;
    }

    /*****created*****/
    @Column(name = "created")
    public Date getCreated(){
        return created;
    }

    public void setCreated(Date created){
        this.created = created;
    }

    public void setCreated(String created){
        try{
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            formatter.setLenient(true);
            this.created = formatter.parse(created);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for Created", e);
        }
    }

    /*****updatedBy*****/
    @Column(name = "updated_by")
    public String getUpdatedBy(){
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy){
        this.updatedBy = updatedBy;
    }

    /*****updated*****/
    @Column(name = "updated")
    public Date getUpdated(){
        return updated;
    }

    public void setUpdated(Date updated){
        this.updated = updated;
    }

    public void setUpdated(String updated){
        try{
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            formatter.setLenient(true);
            this.updated = formatter.parse(updated);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for Updated", e);
        }
    }

    /*****tasks*****/
    @OneToMany(fetch = FetchType.LAZY,   mappedBy = "property", targetEntity=Task.class, cascade=CascadeType.REMOVE)
    public Set<Task> getTasks(){
        return tasks;
    }

    public void setTasks(Set<Task> tasks){
        this.tasks = tasks;
    }

    /*****location*****/
    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Location.class )
    @JoinColumn(name = "location_id",nullable = true)
    public Location getLocation(){
        return location;
    }

    public void setLocation(Location location){
        this.location = location;
    }


}
