package com.schappet.inv.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.inv.domain.*;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import edu.uiowa.icts.util.SortColumn;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.criterion.Restrictions;

/**
 * Generated by Protogen 
 * @date 07/03/2014 12:55:47 CDT
 */
@Repository("com_schappet_inv_dao_LocationHome")
@Transactional
public class LocationHome extends GenericDao<Location> implements LocationService {

    private static final Log log = LogFactory.getLog( LocationHome.class );

    public LocationHome() {
        setDomainName( "com.schappet.inv.domain.Location" );
    }

    public Location findById( Integer id ) {
        return (Location) this.sessionFactory.getCurrentSession().get( getDomainName(), id );
    }

}