package com.schappet.inv.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.inv.domain.*;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import edu.uiowa.icts.util.SortColumn;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.criterion.Restrictions;

/**
 * Generated by Protogen 
 * @date 07/03/2014 12:55:47 CDT
 */
@Repository("com_schappet_inv_dao_PersonHome")
@Transactional
public class PersonHome extends GenericDao<Person> implements PersonService {

    private static final Log log = LogFactory.getLog( PersonHome.class );

    public PersonHome() {
        setDomainName( "com.schappet.inv.domain.Person" );
    }

    public Person findById( Integer id ) {
        return (Person) this.sessionFactory.getCurrentSession().get( getDomainName(), id );
    }

}