package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_LocationHome" )
public class LocationHome extends GenericDao<Location> implements LocationService {

	public LocationHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.Location" );
	}

	public Location findById( Integer id ) {
		return (Location) this.sessionFactory.getCurrentSession().get( Location.class, id );
	}

}