package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
public interface SystemSettingService extends GenericDaoInterface<SystemSetting> {

	public SystemSetting findById( String id );

	public String getValue( String name, String defaultVal );

}