package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/18/2015 07:52:59 CDT
 */
public interface TaskTypeService extends GenericDaoInterface<TaskType> {

	public TaskType findById( Integer id );

}