package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.inv.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/18/2015 07:52:59 CDT
 */
@Transactional
@Repository( "edu_uiowa_icts_inv_dao_TaskTypeHome" )
public class TaskTypeHome extends GenericDao<TaskType> implements TaskTypeService {

	public TaskTypeHome() {
		setDomainName( "edu.uiowa.icts.inv.domain.TaskType" );
	}

	public TaskType findById( Integer id ) {
		return (TaskType) this.sessionFactory.getCurrentSession().get( TaskType.class, id );
	}

}