package edu.uiowa.icts.inv.dao;

import edu.uiowa.icts.spring.*;

import java.util.List;

import edu.uiowa.icts.inv.domain.*;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
public interface TaskService extends GenericDaoInterface<Task> {

	public Task findById( Integer id );

	public List<Task> listByPerson(String username);

}