package edu.uiowa.icts.inv.resource;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:57 CDT
 */
@RestController
@RequestMapping( "/api" )
public class DefaultResource extends AbstractInvApiResource {

	@RequestMapping( value = "/**" , produces = MediaType.APPLICATION_JSON_VALUE )
	public ResponseEntity<Map<String, Object>> mappingNotFound( HttpServletRequest request ) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put( "message", request.getRequestURI() + " could not be found." );
		return new ResponseEntity<Map<String, Object>>( map, HttpStatus.NOT_FOUND );
	}

	
	@ResponseBody
	@RequestMapping( value = {"/",""} , produces = MediaType.APPLICATION_JSON_VALUE )
	public String index(  ) {
		
		
		return "{}";
	}

}
