package edu.uiowa.icts.inv.resource;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @since ${date}
 */
@RestController
@RequestMapping( "/api/personrole" )
public class PersonRoleResource extends AbstractInvApiResource {

    private static final Log log = LogFactory.getLog( PersonRoleResource.class );
    
    @RequestMapping( value = { "{personRoleId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public PersonRole get(@PathVariable( "personRoleId" ) Integer personRoleId ) {
    	 PersonRole personRole = invDaoService.getPersonRoleService().findById( personRoleId );
		 if (personRole == null){
			 throw new EntityNotFoundException();
		 } 
	     return personRole;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public PersonRole create(@RequestBody @Valid PersonRole personRole ) {
		 invDaoService.getPersonRoleService().save( personRole );
		 return personRole;
    }
    
    @RequestMapping( value = { "{personRoleId}" }, method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public PersonRole update(@PathVariable( "personRoleId" ) Integer personRoleId, @RequestBody @Valid PersonRole personRole ) {
    	PersonRole personRoleRecord = invDaoService.getPersonRoleService().findById( personRoleId );
    	if (personRoleRecord == null || !personRoleRecord.getPersonRoleId().equals(personRole.getPersonRoleId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 invDaoService.getPersonRoleService().getSession().flush();
         invDaoService.getPersonRoleService().getSession().clear();
		 invDaoService.getPersonRoleService().update( personRole );
		 return personRole;
    }
    
    @RequestMapping( value = { "{personRoleId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete(@PathVariable( "personRoleId" ) Integer personRoleId ) {
    	PersonRole personRole = invDaoService.getPersonRoleService().findById( personRoleId );
		 if (personRole == null){
			 throw new EntityNotFoundException();
		 } 
		 invDaoService.getPersonRoleService().delete(personRole);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<PersonRole> list() {
    	 return invDaoService.getPersonRoleService().list();
    }

}