package edu.uiowa.icts.inv.resource;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 10/18/2015 07:52:59 CDT
 */
@RestController( value = "edu_uiowa_icts_inv_resource_tasktype_resource" )
@RequestMapping( "/api/tasktype" )
public class TaskTypeResource extends AbstractInvApiResource {

    private static final Log log = LogFactory.getLog( TaskTypeResource.class );
    
    @RequestMapping( value = { "{taskTypeId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public TaskType get( @PathVariable( "taskTypeId" ) Integer taskTypeId ) {
    	 TaskType taskType = invDaoService.getTaskTypeService().findById( taskTypeId );
		 if (taskType == null){
			 throw new EntityNotFoundException();
		 } 
	     return taskType;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public TaskType create( @RequestBody @Valid TaskType taskType ) {
		 invDaoService.getTaskTypeService().save( taskType );
		 return taskType;
    }
    
    @RequestMapping( value = { "{taskTypeId}" }, method = { RequestMethod.POST, RequestMethod.PUT }, produces = MediaType.APPLICATION_JSON_VALUE  )
    public TaskType update( @PathVariable( "taskTypeId" ) Integer taskTypeId, @RequestBody @Valid TaskType taskType ) {
    	TaskType taskTypeRecord = invDaoService.getTaskTypeService().findById( taskTypeId );
    	if ( taskTypeRecord == null || !taskTypeRecord.getTypeId().equals(taskType.getTypeId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 invDaoService.getTaskTypeService().getSession().flush();
         invDaoService.getTaskTypeService().getSession().clear();
		 invDaoService.getTaskTypeService().update( taskType );
		 return taskType;
    }
    
    @RequestMapping( value = { "{taskTypeId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete( @PathVariable( "taskTypeId" ) Integer taskTypeId ) {
    	TaskType taskType = invDaoService.getTaskTypeService().findById( taskTypeId );
		 if ( taskType == null ){
			 throw new EntityNotFoundException();
		 } 
		 invDaoService.getTaskTypeService().delete(taskType);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<TaskType> list() {
    	 return invDaoService.getTaskTypeService().list();
    }

}