package edu.uiowa.icts.inv.resource;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import edu.uiowa.icts.inv.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @since ${date}
 */
@RestController
@RequestMapping( "/api/person" )
public class PersonResource extends AbstractInvApiResource {

    private static final Log log = LogFactory.getLog( PersonResource.class );
    
    @RequestMapping( value = { "{personId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public Person get(@PathVariable( "personId" ) Integer personId ) {
    	 Person person = invDaoService.getPersonService().findById( personId );
		 if (person == null){
			 throw new EntityNotFoundException();
		 } 
	     return person;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Person create(@RequestBody @Valid Person person ) {
		 invDaoService.getPersonService().save( person );
		 return person;
    }
    
    @RequestMapping( value = { "{personId}" }, method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Person update(@PathVariable( "personId" ) Integer personId, @RequestBody @Valid Person person ) {
    	Person personRecord = invDaoService.getPersonService().findById( personId );
    	if (personRecord == null || !personRecord.getPersonId().equals(person.getPersonId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 invDaoService.getPersonService().getSession().flush();
         invDaoService.getPersonService().getSession().clear();
		 invDaoService.getPersonService().update( person );
		 return person;
    }
    
    @RequestMapping( value = { "{personId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete(@PathVariable( "personId" ) Integer personId ) {
    	Person person = invDaoService.getPersonService().findById( personId );
		 if (person == null){
			 throw new EntityNotFoundException();
		 } 
		 invDaoService.getPersonService().delete(person);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<Person> list() {
    	 return invDaoService.getPersonService().list();
    }

}