package com.schappet.inv.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import com.schappet.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @date 07/03/2014 13:14:00 CDT
 */ 

@Entity(name="com_schappet_inv_domain_message")
@Table(name = "message", schema="inv")
public class Message { 

	private static final Log log = LogFactory.getLog(Message.class);

        private Integer messageId;
        private String messageName;
        private String messageType;
        private Integer version;
        private String messageText;
        private Boolean irbApproval;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date irbApprovalStartDate;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date irbApprovalEndDate;
        private String description;

    public Message()    {
        this.messageId = null;
        this.messageName = "";
        this.messageType = "";
        this.version = null;
        this.messageText = "";
        this.irbApproval = null;
        this.irbApprovalStartDate = null;
        this.irbApprovalEndDate = null;
        this.description = "";
    }

    public Message(Integer messageId, String messageName, String messageType, Integer version, String messageText, Boolean irbApproval, Date irbApprovalStartDate, Date irbApprovalEndDate, String description)
    {
        this.messageId = messageId;
        this.messageName = messageName;
        this.messageType = messageType;
        this.version = version;
        this.messageText = messageText;
        this.irbApproval = irbApproval;
        this.irbApprovalStartDate = irbApprovalStartDate;
        this.irbApprovalEndDate = irbApprovalEndDate;
        this.description = description;
    }

    /*****messageId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="inv.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "message_id", unique = true, nullable = false)
    public Integer getMessageId(){
        return messageId;
    }

    public void setMessageId(Integer messageId){
        this.messageId = messageId;
    }

    /*****messageName*****/
    @Column(name = "message_name")
    public String getMessageName(){
        return messageName;
    }

    public void setMessageName(String messageName){
        this.messageName = messageName;
    }

    /*****messageType*****/
    @Column(name = "message_type")
    public String getMessageType(){
        return messageType;
    }

    public void setMessageType(String messageType){
        this.messageType = messageType;
    }

    /*****version*****/
    @Column(name = "version")
    public Integer getVersion(){
        return version;
    }

    public void setVersion(Integer version){
        this.version = version;
    }

    /*****messageText*****/
    @Column(name = "message_text")
    public String getMessageText(){
        return messageText;
    }

    public void setMessageText(String messageText){
        this.messageText = messageText;
    }

    /*****irbApproval*****/
    @Column(name = "irb_approval")
    public Boolean getIrbApproval(){
        return irbApproval;
    }

    public void setIrbApproval(Boolean irbApproval){
        this.irbApproval = irbApproval;
    }

    /*****irbApprovalStartDate*****/
    @Column(name = "irb_approval_start_date")
    public Date getIrbApprovalStartDate(){
        return irbApprovalStartDate;
    }

    public void setIrbApprovalStartDate(Date irbApprovalStartDate){
        this.irbApprovalStartDate = irbApprovalStartDate;
    }

    public void setIrbApprovalStartDate(String irbApprovalStartDate){
        try{
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            formatter.setLenient(true);
            this.irbApprovalStartDate = formatter.parse(irbApprovalStartDate);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for IrbApprovalStartDate", e);
        }
    }

    /*****irbApprovalEndDate*****/
    @Column(name = "irb_approval_end_date")
    public Date getIrbApprovalEndDate(){
        return irbApprovalEndDate;
    }

    public void setIrbApprovalEndDate(Date irbApprovalEndDate){
        this.irbApprovalEndDate = irbApprovalEndDate;
    }

    public void setIrbApprovalEndDate(String irbApprovalEndDate){
        try{
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            formatter.setLenient(true);
            this.irbApprovalEndDate = formatter.parse(irbApprovalEndDate);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for IrbApprovalEndDate", e);
        }
    }

    /*****description*****/
    @Column(name = "description")
    public String getDescription(){
        return description;
    }

    public void setDescription(String description){
        this.description = description;
    }


}
