package com.schappet.inv.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.inv.domain.*;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import edu.uiowa.icts.util.SortColumn;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import org.hibernate.criterion.Restrictions;

/**
 * Generated by Protogen
 * Fri Jun 27 07:27:13 CDT 2014
 */
@Repository("com_schappet_inv_dao_SystemSettingHome")
@Transactional
public class SystemSettingHome extends GenericDao<SystemSetting> implements SystemSettingService {

    private static final Log log = LogFactory.getLog(SystemSettingHome.class);

    public SystemSettingHome() {
        setDomainName("com.schappet.inv.domain.SystemSetting");
    }

    public SystemSetting findById(String id) {
        return (SystemSetting)this.sessionFactory.getCurrentSession().get(getDomainName(), id);
    }

    public String getValue(String name, String defaultVal){
        Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(SystemSetting.class);
        criteria.add(Restrictions.eq("name", name));
        SystemSetting set = (SystemSetting) criteria.uniqueResult();
        if (set != null) {
            return set.getValue();
        } else {
            return defaultVal;
        }
    }
}