package edu.uiowa.icts.inv.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.inv.domain.Property;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @since 10/16/2015 11:14:56 CDT
 */
@Controller( value = "edu_uiowa_icts_inv_controller_property_controller" )
@RequestMapping( "/property" )
public class PropertyController extends AbstractInvController {

    private static final Log log = LogFactory.getLog( PropertyController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "propertyList", invDaoService.getPropertyService().list() );
        return "/inv/property/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/inv/property/list";
    }

	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		DataTable dt = new DataTable();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = invDaoService.getPropertyService().count( options );
            List<Property> propertyList = invDaoService.getPropertyService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( Property property : propertyList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					if( StringUtils.equals( "propertyId", headerName ) ){
						tableRow.put( dataName, property.getPropertyId() );
					} else if( StringUtils.equals( "name", headerName ) ){
						tableRow.put( dataName, property.getName() );
					} else if( StringUtils.equals( "description", headerName ) ){
						tableRow.put( dataName, property.getDescription() );
					} else if( StringUtils.equals( "createdBy", headerName ) ){
						tableRow.put( dataName, property.getCreatedBy() );
					} else if( StringUtils.equals( "created", headerName ) ){
						tableRow.put( dataName, property.getCreatedString() );
					} else if( StringUtils.equals( "updatedBy", headerName ) ){
						tableRow.put( dataName, property.getUpdatedBy() );
					} else if( StringUtils.equals( "updated", headerName ) ){
						tableRow.put( dataName, property.getUpdatedString() );
					} else if( StringUtils.equals( "tasks", headerName ) ){
						tableRow.put( dataName, property.getTasks().size() );
					} else if( StringUtils.equals( "location", headerName ) ){
						if( property.getLocation() != null ){
							tableRow.put( dataName, property.getLocation().toString() );
						}
					} else if( StringUtils.equals( "urls", headerName ) ) {
						String urls = "";
						if( StringUtils.equals( "list", display ) ){
							urls += "<a href=\"" + contextPath + "/property/show?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
							urls += "<a href=\"" + contextPath + "/property/edit?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
							urls += "<a href=\"" + contextPath + "/property/delete?"+"propertyId="+property.getPropertyId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
						} else {

						}
						tableRow.put( dataName, urls );
					} else {
						tableRow.put( "error", "[error: column " + headerName + " not supported]" );
					}
				}
				data.add( tableRow );
			}

			dt.setDraw( dataTableRequest.getDraw() );
            dt.setRecordsFiltered( count );
            dt.setRecordsTotal( count );
			dt.setData( data );

		} catch ( Exception e ) {
			log.error( "error builing datatable json object for Property", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
		return dt;
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "property", new Property() );
		model.addAttribute( "locationList", invDaoService.getLocationService().list() );

        return "/inv/property/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {
		model.addAttribute( "locationList", invDaoService.getLocationService().list() );


        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "property" ) Property property, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "locationList", invDaoService.getLocationService().list() );

			return "/inv/property/edit"; 
		} else {
			if (property.getCreated() == null) {
				property.setCreated(new Date());
				property.setCreatedBy(getUsername());
			} else {
				property.setUpdated(new Date());
				property.setUpdatedBy(getUsername());

			}
				
			try {
				invDaoService.getPropertyService().saveOrUpdate( property );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				invDaoService.getPropertyService().merge( property );
			}
		}
		return "redirect:/property/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        model.addAttribute( "property", invDaoService.getPropertyService().findById( propertyId ) );
        return "/inv/property/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "propertyId" ) Integer propertyId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            invDaoService.getPropertyService().delete( invDaoService.getPropertyService().findById( propertyId ) );
        }
        return "redirect:/property/list";
    }
}